"""End-to-end tests for the five graduation verbs, driven through the real CLI.

These exist because of a specific failure: ``export``, ``train``, ``evaluate``,
``package`` and ``graduate`` were all registered in :mod:`jev_route.cli` and all
five raised ``AttributeError: module 'jev_route.distill' has no attribute
'export_cli'``. The parser was complete, ``--help`` looked finished, and the
headline feature was 100% broken. A unit test of any one verb would not have
caught that, because the break was in the seam between the two modules -- so the
first test here drives ``jev_route.cli.main`` exactly as a shell would, and the
rest walk the whole lifecycle on a real log.

The log is generated by :mod:`tests.distill.synthlog`, which routes a prompt
corpus through the real Router with MockBackend, so the records being exported
are records the production code path could have written. No network, no API key:
``conftest.py``'s autouse ``_offline`` fixture removes the key and fails any
socket call, and every path below is inside ``tmp_path``.

What is deliberately *not* asserted: that the trained student is any good. It is
trained on ~120 synthetic decisions, so its tier agreement is nowhere near the
0.95 bar. The tests assert the verbs run, report, exit with the documented codes,
and refuse to write a policy they have not earned -- which is the behaviour under
test. ``tests/backends/test_distilled.py`` covers serving an artifact.
"""

from __future__ import annotations

import contextlib
import io
import json
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import pytest

from jev_route.cli import main
from tests.distill.synthlog import build_log

REPO_ROOT = Path(__file__).resolve().parents[1]
TRACEBACK = "Traceback (most recent call last)"
ENV_VARS = ("JEV_ROUTE_POLICY", "JEV_ROUTE_LOG", "JEV_ROUTE_DECISION_LOG", "JEV_ROUTE_ARTIFACT")


def _clean_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """A leaked JEV_ROUTE_* would silently change which policy or log a verb picks."""
    for name in ENV_VARS:
        monkeypatch.delenv(name, raising=False)


def _require_numpy() -> None:
    try:
        import numpy  # noqa: F401
    except ImportError:  # pragma: no cover - depends on the environment
        pytest.skip("the distill extra is not installed: pip install 'jev-route[distill]'")


def run(argv: Sequence[str]) -> tuple[int, str, str]:
    """Run the CLI in-process and capture both streams.

    In-process rather than a subprocess because that is what makes a traceback
    visible as a test failure instead of a wall of stderr, and because it keeps
    the whole lifecycle inside one pytest session's import cache.
    """
    out, err = io.StringIO(), io.StringIO()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
        code = main(list(argv))
    return int(code), out.getvalue(), err.getvalue()


def run_json(argv: Sequence[str]) -> tuple[int, dict[str, Any], str]:
    """Run a verb with ``--json`` and parse stdout, which must be nothing but JSON."""
    code, out, err = run([*argv, "--json"])
    try:
        return code, json.loads(out), err
    except json.JSONDecodeError as exc:  # pragma: no cover - a real failure, not a skip
        pytest.fail(f"--json printed something that is not JSON ({exc}):\n{out[:800]}")


@pytest.fixture(autouse=True)
def _isolated(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """Run from a directory with no policy file, so no test inherits the repo's."""
    _clean_env(monkeypatch)
    monkeypatch.chdir(tmp_path)


@pytest.fixture(scope="module")
def log_path(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A real decision log: 140 records routed through the real Router, offline."""
    _require_numpy()
    target = tmp_path_factory.mktemp("logs") / "decisions.jsonl"
    # The log has to be written where the verbs will look for it, and the fixture
    # directory is not the per-test cwd, so it is built at an absolute path.
    stats = build_log(target, n=140, seed=11, excerpt_mode="hash")
    assert stats.records == 140
    return target


@pytest.fixture(scope="module")
def lifecycle(tmp_path_factory: pytest.TempPathFactory, log_path: Path) -> dict[str, Any]:
    """Run the whole lifecycle once, and hand every stage's result to the tests.

    One run rather than one per test because training dominates the cost, and
    because the point is that the stages chain: ``train`` reads what ``export``
    wrote, ``evaluate`` and ``package`` read what ``train`` wrote, and
    ``graduate`` reads what ``package`` wrote. A fixture per stage would let a
    broken hand-off pass unnoticed.
    """
    work = tmp_path_factory.mktemp("lifecycle")
    results: dict[str, Any] = {"work": work}

    results["export"] = run(["export", "--log", str(log_path), "--out", str(work / "ds")])
    dataset = work / "ds" / "dataset.jsonl"
    results["dataset"] = dataset
    assert dataset.is_file(), results["export"][2] or results["export"][1]

    results["train"] = run(["train", "--data", str(work / "ds"), "--out", str(work / "v1")])
    results["model"] = work / "v1"
    assert (work / "v1" / "artifact.json").is_file(), results["train"][2] or results["train"][1]

    results["evaluate"] = run(["evaluate", "--artifact", str(work / "v1")])
    results["evaluate_json"] = run_json(["evaluate", "--artifact", str(work / "v1")])

    results["package"] = run(["package", "--artifact", str(work / "v1"), "--out", str(work / "packaged")])
    results["artifact"] = work / "packaged"
    assert (work / "packaged" / "artifact.json").is_file(), results["package"][2] or results["package"][1]

    results["graduate"] = run(["graduate", "--artifact", str(work / "packaged"), "--min-samples", "1"])
    results["graduate_json"] = run_json(["graduate", "--artifact", str(work / "packaged"), "--min-samples", "1"])
    return results


# --------------------------------------------------------------------------- #
# the seam that was broken
# --------------------------------------------------------------------------- #
class TestTheVerbsAreWiredUp:
    """The regression test for five commands that parsed and did not exist."""

    @pytest.mark.parametrize(
        "verb",
        ["label_sensitivity_cli", "export_cli", "train_cli", "evaluate_cli", "package_cli", "graduate_cli"],
    )
    def test_the_package_exposes_the_verb(self, verb: str) -> None:
        from jev_route import distill

        assert callable(getattr(distill, verb)), f"jev_route.distill.{verb} is missing or not callable"

    def test_the_lazy_export_does_not_import_numpy(self) -> None:
        """``import jev_route`` has to stay numpy-free: the router runs in containers without it."""
        code = (
            "import sys, jev_route.distill as d;"
            "names = [getattr(d, n).__name__ for n in d.__all__];"
            "print(','.join(sorted(names)), 'numpy' in sys.modules)"
        )
        result = subprocess.run(
            [sys.executable, "-c", code], capture_output=True, text=True, timeout=120, cwd=str(REPO_ROOT)
        )
        assert result.returncode == 0, result.stderr
        names, numpy_loaded = result.stdout.strip().split()
        assert names == "evaluate_cli,export_cli,graduate_cli,label_sensitivity_cli,package_cli,train_cli"
        assert numpy_loaded == "False", "resolving the six verbs pulled numpy into the process"

    def test_export_runs_from_a_cold_start(self, log_path: Path, tmp_path: Path) -> None:
        """``export`` needs no numpy at all, so it works even without the extra."""
        code, out, err = run(["export", "--log", str(log_path), "--out", str(tmp_path / "cold")])
        assert code == 0, err or out
        assert TRACEBACK not in out + err


# --------------------------------------------------------------------------- #
# the lifecycle
# --------------------------------------------------------------------------- #
class TestTheLifecycle:
    def test_every_stage_exits_zero(self, lifecycle: dict[str, Any]) -> None:
        for stage in ("export", "train", "evaluate", "package"):
            code, out, err = lifecycle[stage]
            assert code == 0, f"{stage} exited {code}: {err or out}"

    def test_no_stage_printed_a_traceback(self, lifecycle: dict[str, Any]) -> None:
        for stage in ("export", "train", "evaluate", "package"):
            _, out, err = lifecycle[stage]
            assert TRACEBACK not in out + err, f"{stage} leaked a traceback"

    def test_export_reports_the_rows_it_kept(self, lifecycle: dict[str, Any]) -> None:
        _, out, _ = lifecycle["export"]
        assert "dataset" in out.lower()
        rows = [line for line in lifecycle["dataset"].read_text(encoding="utf-8").splitlines() if line.strip()]
        assert len(rows) > 100, f"the export kept only {len(rows)} of 140 records"
        first = json.loads(rows[0])
        assert "features" in first or "text" in first

    def test_train_writes_an_artifact_directory(self, lifecycle: dict[str, Any]) -> None:
        model = lifecycle["model"]
        from jev_route.distill.artifact import ARTIFACT_KIND, ARTIFACT_SCHEMA_VERSION

        envelope = json.loads((model / "artifact.json").read_text(encoding="utf-8"))
        # Compared against the library's constants, not a literal copied from the docs:
        # the kind string is the loader's contract, and a test that hardcodes it would
        # keep passing after the loader stopped accepting it.
        assert envelope["kind"] == ARTIFACT_KIND
        assert envelope["artifact_schema_version"] == ARTIFACT_SCHEMA_VERSION
        assert envelope["mode"] == "features"
        assert envelope["contains_prompt_text"] is False, "a hash-mode log has no text to retain"
        assert sorted(model.glob("*.npy")), "the weights are not on disk"

    def test_evaluate_reports_the_four_heads(self, lifecycle: dict[str, Any]) -> None:
        _, payload, _ = lifecycle["evaluate_json"]
        heads = payload["report"]["heads"] if "report" in payload else payload["heads"]
        assert set(heads) >= {"complexity", "sensitivity", "domain", "pii"}

    def test_package_embeds_metrics_and_verifies_its_own_output(self, lifecycle: dict[str, Any]) -> None:
        _, out, _ = lifecycle["package"]
        assert "no pickle anywhere" in out
        artifact = lifecycle["artifact"]
        assert (artifact / "metrics.json").is_file(), "the packaged artifact carries no metrics.json"
        envelope = json.loads((artifact / "artifact.json").read_text(encoding="utf-8"))
        assert envelope["packaged_from"], "the artifact does not say what it was packaged from"

    def test_package_json_names_the_files_it_wrote(self, lifecycle: dict[str, Any]) -> None:
        code, payload, err = run_json(
            ["package", "--artifact", str(lifecycle["model"]), "--out", str(lifecycle["work"] / "packaged-json")]
        )
        assert code == 0, err
        assert payload["metrics_embedded"] is True
        assert set(payload["files"]) >= {"artifact.json", "metrics.json"}
        assert payload["bytes"] == sum(payload["files"].values())


# --------------------------------------------------------------------------- #
# graduate: the verdict is the product
# --------------------------------------------------------------------------- #
class TestGraduation:
    def test_the_documented_gates_are_not_met_by_a_small_synthetic_model(self, lifecycle: dict[str, Any]) -> None:
        """Exit 1 and nothing written. A student trained on 140 mock decisions cannot graduate."""
        code, out, err = run(["graduate", "--artifact", str(lifecycle["artifact"])])
        assert code == 1, f"expected NOT READY, got {code}: {err or out}"
        assert "NOT READY" in out
        assert "min_samples" in out
        assert "WARNING" not in out, "no gate was relaxed, so there is nothing to warn about"
        assert not list(lifecycle["work"].glob("*graduated*")), "a policy was written by a run without --write"

    def test_the_gates_table_shows_requirement_and_measurement(self, lifecycle: dict[str, Any]) -> None:
        _, out, _ = lifecycle["graduate"]
        for gate in ("min_tier_agreement", "max_ece", "max_latency_ms", "min_samples"):
            assert gate in out, f"{gate} is missing from the report"
        assert "[ pass ]" in out or "[ FAIL ]" in out

    def test_a_relaxed_gate_is_never_silent(self, lifecycle: dict[str, Any]) -> None:
        """A READY verdict bought by moving the goalposts has to say so, loudly."""
        code, out, _ = run(
            [
                "graduate",
                "--artifact",
                str(lifecycle["artifact"]),
                "--min-tier-agreement",
                "0.0",
                "--max-ece",
                "1.0",
                "--max-latency-ms",
                "100000",
                "--min-samples",
                "1",
            ]
        )
        assert code == 0
        assert "VERDICT: READY" in out
        assert "WARNING" in out
        assert "NOT a promotion" in out
        for gate in ("min_tier_agreement", "max_ece", "max_latency_ms", "min_samples"):
            assert f"- {gate}:" in out, f"{gate} was relaxed but not reported"

    def test_the_relaxed_gates_appear_in_the_json_too(self, lifecycle: dict[str, Any]) -> None:
        _, payload, _ = lifecycle["graduate_json"]
        assert [line.split(":")[0] for line in payload["gates_relaxed"]] == ["min_samples"]
        assert payload["wrote"] is None, "--json without --write must not claim a swap"

    def test_relaxing_one_gate_does_not_buy_a_pass(self, lifecycle: dict[str, Any]) -> None:
        """``--min-samples 1`` alone still leaves the student short of the other three gates."""
        _, payload, _ = lifecycle["graduate_json"]
        assert payload["ready"] is False
        failed = [c["name"] for c in payload["checks"] if not c["passed"]]
        assert "min_samples" not in failed
        assert failed, "at least one gate should still fail on 140 synthetic decisions"

    def test_exactly_one_relaxed_gate_reports_exactly_one_line(self, lifecycle: dict[str, Any]) -> None:
        _, out, _ = lifecycle["graduate"]
        assert "WARNING: 1 of the 4 gates were relaxed" in out
        assert out.count("in the docs") == 1
        assert "min_samples: 1 on the command line, 500 in the docs (floor lowered)" in out

    def test_tightening_a_gate_is_not_reported_as_relaxing_it(self, lifecycle: dict[str, Any]) -> None:
        code, out, _ = run(
            ["graduate", "--artifact", str(lifecycle["artifact"]), "--max-ece", "0.01", "--min-samples", "500"]
        )
        assert code == 1
        assert "WARNING" not in out, "a stricter gate cannot manufacture a pass, so it is not a relaxation"

    def test_write_refuses_when_a_gate_fails(self, lifecycle: dict[str, Any]) -> None:
        code, out, err = run(
            ["graduate", "--artifact", str(lifecycle["artifact"]), "--write", "--out-policy", "refused.yaml"]
        )
        assert code == 1, err or out
        assert not Path("refused.yaml").exists()
        assert "Nothing was written" in out or "not ready" in out.lower()

    def test_write_under_relaxed_gates_produces_a_servable_policy(self, lifecycle: dict[str, Any]) -> None:
        """The cutover itself: a new file, the local model as primary, the teacher as shadow."""
        dest = Path("graduated-relaxed.yaml")
        code, out, err = run(
            [
                "graduate",
                "--artifact",
                str(lifecycle["artifact"]),
                "--min-tier-agreement",
                "0.0",
                "--max-ece",
                "1.0",
                "--max-latency-ms",
                "100000",
                "--min-samples",
                "1",
                "--write",
                "--out-policy",
                str(dest),
            ]
        )
        assert code == 0, err or out
        assert dest.is_file()
        import yaml

        written = yaml.safe_load(dest.read_text(encoding="utf-8"))
        backend = written["backend"]
        assert backend["name"] == "shadow"
        assert backend["primary"]["name"] == "distilled"
        assert Path(backend["primary"]["artifact"]) == lifecycle["artifact"].resolve()
        assert backend["primary"]["feature_mode"] is True
        assert "primary builds DistilledBackend" in out, "the swap was not verified against the real factory"

    def test_the_written_policy_is_not_the_one_it_graduated_from(self, lifecycle: dict[str, Any]) -> None:
        code, out, _ = run(
            [
                "graduate",
                "--artifact",
                str(lifecycle["artifact"]),
                "--min-tier-agreement",
                "0.0",
                "--max-ece",
                "1.0",
                "--max-latency-ms",
                "100000",
                "--min-samples",
                "1",
                "--write",
            ]
        )
        assert code == 0
        assert "(new file)" in out
        assert not (REPO_ROOT / "policies" / "default-graduated.yaml").exists() or "new file" in out


# --------------------------------------------------------------------------- #
# argument handling
# --------------------------------------------------------------------------- #
class TestArgumentHandling:
    def test_the_deprecated_model_alias_still_works_and_says_so(self, lifecycle: dict[str, Any]) -> None:
        code, out, err = run(
            ["package", "--model", str(lifecycle["model"]), "--out", str(lifecycle["work"] / "via-alias")]
        )
        assert code == 0, err or out
        assert "--model is a deprecated alias for --artifact" in err
        assert "0.3.0" in err
        assert (lifecycle["work"] / "via-alias" / "artifact.json").is_file()
        assert "warning" not in out, "the warning belongs on stderr so --json stays parseable"

    def test_the_alias_warning_does_not_corrupt_json(self, lifecycle: dict[str, Any]) -> None:
        code, payload, err = run_json(
            ["package", "--model", str(lifecycle["model"]), "--out", str(lifecycle["work"] / "alias-json")]
        )
        assert code == 0, err
        assert "deprecated alias" in err
        assert payload["artifact"].endswith("alias-json")

    def test_the_new_spelling_does_not_warn(self, lifecycle: dict[str, Any]) -> None:
        code, _, err = run(
            ["package", "--artifact", str(lifecycle["model"]), "--out", str(lifecycle["work"] / "no-warn")]
        )
        assert code == 0, err
        assert "deprecated" not in err

    @pytest.mark.parametrize(
        ("argv", "needle"),
        [
            pytest.param(["package", "--out", "x"], "needs the trained model", id="neither-flag"),
            pytest.param(
                ["package", "--artifact", "a", "--model", "b", "--out", "x"],
                "not both",
                id="both-and-they-disagree",
            ),
        ],
    )
    def test_an_ambiguous_package_invocation_is_refused(self, argv: list[str], needle: str) -> None:
        code, out, err = run(argv)
        assert code == 2
        assert needle in err, err or out
        assert TRACEBACK not in out + err

    def test_both_flags_naming_the_same_path_is_not_an_error(self, lifecycle: dict[str, Any]) -> None:
        model = str(lifecycle["model"])
        code, _, err = run(["package", "--artifact", model, "--model", model, "--out", "same-path"])
        assert code == 0, err
        assert "deprecated" not in err, "--artifact was given, so the alias is not what the operator used"

    def test_an_explicit_policy_that_does_not_exist_is_an_error(self, lifecycle: dict[str, Any]) -> None:
        """Not a silent fallback: the gates are measured under the policy you named."""
        for argv in (
            ["graduate", "--artifact", str(lifecycle["artifact"]), "--policy", "nope.yaml"],
            ["evaluate", "--artifact", str(lifecycle["artifact"]), "--policy", "nope.yaml"],
        ):
            code, out, err = run(argv)
            assert code == 2, err or out
            assert "does not exist" in err
            assert TRACEBACK not in out + err


# --------------------------------------------------------------------------- #
# failure paths: one line, no traceback, exit 2
# --------------------------------------------------------------------------- #
class TestFailuresAreOneLine:
    @pytest.mark.parametrize(
        ("argv", "needle"),
        [
            pytest.param(["export", "--log", "gone.jsonl", "--out", "ds"], "decision log not found", id="export-log"),
            pytest.param(["train", "--data", "nodata", "--out", "v1"], "dataset not found", id="train-data"),
            pytest.param(["evaluate", "--artifact", "noartifact"], "no distilled artifact", id="evaluate-artifact"),
            pytest.param(
                ["package", "--artifact", "noartifact", "--out", "x"], "no distilled artifact", id="package-artifact"
            ),
            pytest.param(
                ["graduate", "--artifact", "noartifact", "--policy", str(REPO_ROOT / "policies" / "default.yaml")],
                "no distilled artifact",
                id="graduate-artifact",
            ),
        ],
    )
    def test_a_missing_input_is_actionable(self, argv: list[str], needle: str) -> None:
        code, out, err = run(argv)
        assert code == 2
        assert needle in err, err or out
        assert TRACEBACK not in out + err
        assert len([line for line in err.splitlines() if line.startswith("jev-route")]) == 1

    def test_bad_training_numbers_are_rejected_before_any_work(self, log_path: Path, tmp_path: Path) -> None:
        _require_numpy()
        run(["export", "--log", str(log_path), "--out", str(tmp_path / "ds")])
        for flag, value, needle in (
            ("--epochs", "0", "at least 1"),
            ("--lr", "0", "must be in"),
        ):
            code, out, err = run(["train", "--data", str(tmp_path / "ds"), "--out", str(tmp_path / "v"), flag, value])
            assert code == 2, err or out
            assert needle in err
            assert TRACEBACK not in out + err

    def test_replay_on_a_hash_mode_log_explains_why_it_cannot(self, lifecycle: dict[str, Any]) -> None:
        """The log retained no prompt text, so there is nothing to re-send to a teacher."""
        code, out, err = run(["graduate", "--artifact", str(lifecycle["artifact"]), "--replay", "--min-samples", "1"])
        assert code == 2
        combined = out + err
        assert "excerpt_mode" in combined or "redacted" in combined
        assert TRACEBACK not in combined

    def test_library_messages_name_only_real_cli_verbs(self) -> None:
        """Error advice must point at a verb ``jev-route --help`` lists.

        The four library modules were once written against a single ``jev-route
        distill`` verb the CLI never had; that is fixed at the source, so this
        pins it: no module in the package names the stale verb, and the
        load-bearing advice string names the real two-stage lifecycle.
        """
        import jev_route.distill as distill_pkg

        offenders = [py.name for py in sorted(Path(distill_pkg.__file__).resolve().parent.glob("*.py"))
                     if "jev-route distill" in py.read_text(encoding="utf-8")]
        assert offenders == []

        from jev_route.distill import artifact

        with pytest.raises(artifact.ArtifactError) as excinfo:
            artifact.load_artifact("/definitely/absent/artifact")
        assert "jev-route export --log" in str(excinfo.value)
        assert "jev-route train --data" in str(excinfo.value)
