"""LiteLLM classifier plugin: jev-route inside the native complexity router.

LiteLLM ships a complexity router -- a ``model_list`` entry whose
``litellm_params.model`` is ``auto_router/complexity_router`` -- that classifies
each request into a tier and then lets LiteLLM's own machinery pick the
deployment, honour cooldowns, run fallbacks and load balance. With
``classifier_type: custom`` the classification itself is delegated to a
:class:`litellm.types.router.ClassifierPlugin`: an object with an
``async def classify(self, context) -> str | None`` that returns a **tier name**.

Returning a tier name rather than a model is what makes this the most
LiteLLM-native of the three integrations: jev-route supplies the judgement,
LiteLLM keeps every consequence of it. It is also why the plugin returns
``None`` in three separate situations -- a declined decision, an unknown tier, an
internal error -- instead of guessing a tier: ``None`` hands control to the
configured fallback, which the operator chose, rather than to a default this
class invented.

Two things about LiteLLM's own design are worth quoting here, because they are
the reason this file exists in the shape it does.

The docstring of ``ComplexityRouterConfig.classifier_fallback`` says, verbatim:

    'default_model' skips scoring and routes to default_model, which is what a
    classifier on some other taxonomy wants: **a prompt that grades data
    sensitivity has no use for a complexity score**, and scoring one produces a
    tier unrelated to what the operator configured.

That sentence describes jev-route. Its tiers are ``local`` / ``cheap`` /
``strong`` and its first two rules are about data protection, not difficulty.
Note for operators, though: ``classifier_fallback: default_model`` and
``tier_definitions`` are **mutually exclusive** -- LiteLLM rejects the
combination with "classifier_fallback 'default_model' cannot be combined with
tier_definitions: fallback_tier is where a custom-tier router routes when the
classifier fails". With a custom tier set, ``fallback_tier`` *is* that knob, so
``examples/litellm-proxy-classifier/config.yaml`` sets ``fallback_tier: local``
and no ``classifier_fallback``.

One limitation, verified against a running LiteLLM 1.101 proxy rather than
guessed, because it changes what you can do with the resulting dataset: the
``RoutingContext`` a classifier plugin receives carries 51 metadata keys and
**none of them is ``litellm_call_id`` or ``request_id``**. So in this mode the
decision record's ``request_id`` is generated by jev-route and cannot be joined
back to LiteLLM's spend log row for the same request. If a hard join matters to
you -- "which decisions belonged to the requests that were slow, and what did
they cost" -- use the pre-call hook instead, which sees the whole request body
and does pick up ``litellm_call_id``. What this mode gives you in exchange is
LiteLLM's own tier machinery: cooldowns, fallbacks and load balancing inside the
chosen tier, which the hook cannot take part in because the model name is already
fixed by the time it returns.

The other fact: a custom tier set costs you LiteLLM's escalation, adaptive
routing, session affinity, tier labels and the complexity-router plugin
pipeline. That is fine, and deliberate -- jev-route does its own escalation in
the policy engine (``on_uncertain`` bumps complexity and sensitivity *stricter*
when the backend is not confident, which is escalation on evidence rather than
on a retry counter) and its own stickiness through the decision cache.

Interface detail that decides the module's shape: the proxy resolves
``classifier_plugin`` through ``litellm.proxy.types_utils.utils.get_instance_fn``,
whose last dotted segment must be a module *attribute holding an instance*, and
``resolve_classifier_plugin`` then requires
``inspect.iscoroutinefunction(obj.classify)``. Hence the module-level
``classifier`` at the bottom, and hence ``classify`` being a real coroutine
function rather than something returning an awaitable.
"""

from __future__ import annotations

import inspect
import os
from collections.abc import Awaitable, Callable, Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

from ..router import Router
from ..schema import TIERS, RoutingDecision
from . import _shared
from ._shared import LOGGER

#: Tier names this classifier may return when nothing else says otherwise.
TIERS_ENV_VAR = "JEV_ROUTE_CLASSIFIER_TIERS"
DEFAULT_TIERS: tuple[str, ...] = TIERS

#: LiteLLM's own budget for a classifier plugin call, so the default here sits
#: under it and declines on our terms instead of being cancelled on theirs.
DEFAULT_LITELLM_CLASSIFIER_TIMEOUT_MS = 3000
DEFAULT_CLASSIFIER_TIMEOUT_MS = 2500

#: Signature: ``(decision, tier)``. May be sync or async; either is awaited.
DecisionCallback = Callable[[RoutingDecision, str | None], Any]

RouterFactory = Callable[[], Router]


class JevRouteClassifier:
    """A ``ClassifierPlugin`` that answers with a jev-route tier name.

    Args:
        router: an explicit :class:`~jev_route.router.Router` or a factory
            returning one. ``None`` uses the process-wide router, so the
            classifier shares the cache, circuit breaker and decision log with
            every other jev-route integration in the process.
        tiers: the tier names this classifier is allowed to return. Anything
            else becomes ``None`` (decline) so LiteLLM's fallback decides. When
            unset, ``JEV_ROUTE_CLASSIFIER_TIERS`` is read, then the policy's own
            ``tiers:`` keys, then :data:`jev_route.schema.TIERS`. Set it
            explicitly to match your ``tier_definitions`` -- that list is the
            authority LiteLLM validates against, and this one only exists to
            decline early rather than make LiteLLM do it.
        on_decision: optional callback invoked with ``(decision, tier)`` after
            every classification, for operators shipping decisions somewhere
            else in addition to the JSONL log. It cannot break routing: errors
            are caught and logged, and it runs *after* the tier is resolved.
        timeout_ms: internal budget. Kept below LiteLLM's
            ``classifier_plugin_timeout_ms`` so a slow backend produces a clean
            decline instead of an ``asyncio.TimeoutError`` in LiteLLM's logs.
    """

    def __init__(
        self,
        router: Router | RouterFactory | None = None,
        *,
        tiers: Iterable[str] | None = None,
        on_decision: DecisionCallback | None = None,
        timeout_ms: float | None = None,
    ) -> None:
        self._router = router
        self._configured_tiers = _normalize_tiers(tiers) if tiers is not None else None
        self.on_decision = on_decision
        self._timeout_ms = timeout_ms
        self._warned = False

    # -- construction ----------------------------------------------------- #
    @classmethod
    def from_env(cls, **kwargs: Any) -> JevRouteClassifier:
        """Build from the environment without ever raising.

        The proxy resolves this at startup. A missing policy file or a missing
        ``TYPESAFE_API_KEY`` must not stop it booting, so the router is built
        lazily and its own construction degrades to the built-in policy on
        MockBackend (see :func:`._shared.build_router`). The warning is emitted
        here, at startup, rather than on the first request, because "your proxy
        is routing on coarse offline judgements" is the one thing an operator
        needs to see in the boot log.
        """
        env_tiers = os.environ.get(TIERS_ENV_VAR)
        tiers = kwargs.pop("tiers", None)
        if tiers is None and env_tiers:
            tiers = _normalize_tiers(env_tiers)
        instance = cls(tiers=tiers, **kwargs)
        path = _shared.resolve_policy_path()
        if path is None:
            LOGGER.warning(
                "jev-route: no policy file found (set %s); the classifier will run the built-in "
                "policy on the offline MockBackend. Decisions will be coarse but safe.",
                _shared.POLICY_ENV_VAR,
            )
        elif _policy_wants_cloud(path) and not os.environ.get("TYPESAFE_API_KEY"):
            # Only warn when it matters. A policy on MockBackend or on a distilled
            # artifact needs no key, and a boot log that cries about a missing
            # credential on every offline deployment trains operators to ignore it.
            LOGGER.warning(
                "jev-route: policy %s asks for backend.name: jev but TYPESAFE_API_KEY is not set; "
                "the router will fall back to MockBackend and fail closed on uncertainty.",
                path,
            )
        return instance

    # -- internals -------------------------------------------------------- #
    @property
    def router(self) -> Router:
        """The router, resolved on first use so importing this module is free of side effects."""
        if self._router is None:
            self._router = _shared.get_router()
        elif isinstance(self._router, Callable) and not isinstance(self._router, Router):
            self._router = self._router()
        return self._router

    @property
    def tiers(self) -> frozenset[str]:
        """The tier names this classifier will return."""
        if self._configured_tiers is not None:
            return self._configured_tiers
        try:
            return frozenset(str(tier) for tier in self.router.policy.tiers)
        except Exception:  # broad except, deliberately: no router yet; the schema default is safe
            return frozenset(DEFAULT_TIERS)

    def _is_known_tier(self, tier: str) -> bool:
        return tier in self.tiers

    # -- the plugin interface --------------------------------------------- #
    async def classify(self, context: Any) -> str | None:
        """LiteLLM ``ClassifierPlugin.classify``. A tier name, or ``None`` to decline.

        Never raises, for the same reason twice over: LiteLLM already wraps this
        call in ``try/except`` and turns any exception into
        ``classifier_fallback``/``fallback_tier``, so raising would produce the
        same routing outcome with a stack trace in someone's proxy log and no
        jev-route context in it. Declining explicitly keeps the reason ours.

        Note that ``context.candidate_models`` here is an *informational*
        snapshot of every tier's models: unlike the ``RoutingPlugin`` surface,
        mutating it does nothing, because the returned tier decides the pool.
        This class therefore never writes to it.
        """
        decision: RoutingDecision | None = None
        tier: str | None = None
        try:
            decision = await self._decide(context)
            if decision is None:
                return None
            tier = self._tier_for(decision)
            return tier
        except Exception as exc:  # broad except, deliberately: documented: decline, never raise
            LOGGER.warning(
                "jev-route: classifier failed (%s: %s); declining so LiteLLM's fallback tier decides.",
                type(exc).__name__,
                exc,
                exc_info=True,
            )
            return None
        finally:
            self._notify(decision, tier)

    async def _decide(self, context: Any) -> RoutingDecision | None:
        messages = list(getattr(context, "structured_messages", None) or []) or list(
            getattr(context, "raw_messages", None) or []
        )
        raw_metadata = getattr(context, "metadata", None) or {}
        _shared.log_metadata_keys("classifier context", raw_metadata)
        metadata = _shared.filter_metadata(raw_metadata)
        requested_model = metadata.get("model_group") if isinstance(metadata.get("model_group"), str) else None
        if requested_model is None and isinstance(raw_metadata, Mapping):
            for key in ("model_group", "model"):
                if isinstance(raw_metadata.get(key), str):
                    requested_model = raw_metadata[key]
                    break
        timeout = self._timeout_ms
        if timeout is None:
            # Stay under LiteLLM's own budget when the operator left it at the
            # default, so the decline is ours and is logged with a reason.
            timeout = min(_shared.timeout_ms(), DEFAULT_CLASSIFIER_TIMEOUT_MS)
        decision, reason = await _shared.decide_with_reason(
            self.router,
            messages=messages,
            metadata=metadata,
            requested_model=requested_model,
            request_id=_shared.request_id_for(None, metadata),
            timeout_ms=timeout,
        )
        if decision is None:
            LOGGER.info("jev-route: declining to classify (%s).", reason or "no decision")
        return decision

    def _tier_for(self, decision: RoutingDecision) -> str | None:
        """The tier to return, or ``None`` when jev-route's tier is not one of ours.

        Validating here rather than trusting :meth:`Router` is not redundancy for
        its own sake. The policy's tiers and the proxy's ``tier_definitions`` are
        two files maintained by two people; when they drift, returning a tier
        LiteLLM has never heard of costs a ``fallback_tier`` anyway, but it costs
        one *plus* an error line in the proxy log that names jev-route as the
        culprit. Declining with our own warning is the same routing outcome and a
        much better diagnosis.
        """
        tier = decision.tier
        if not tier:
            # A rule pinned a concrete model with no tier (`then: {model: ...}`).
            # A complexity router can only be told a tier, so decline and let the
            # fallback decide rather than inventing one.
            LOGGER.info("jev-route: rule %s pinned a model with no tier; declining.", decision.rule_id)
            return None
        if not self._is_known_tier(tier):
            if not self._warned:
                # Once, not per request: a proxy under load would otherwise log
                # the same config mismatch thousands of times a minute.
                self._warned = True
                LOGGER.warning(
                    "jev-route: policy chose tier %r, which is not in the configured tier set %s; "
                    "declining so LiteLLM's fallback tier decides. Set %s (or the `tiers=` "
                    "constructor argument) to match your complexity_router tier_definitions.",
                    tier,
                    sorted(self.tiers),
                    TIERS_ENV_VAR,
                )
            return None
        return tier

    def _notify(self, decision: RoutingDecision | None, tier: str | None) -> None:
        """Fire ``on_decision`` without letting it affect routing."""
        if self.on_decision is None or decision is None:
            return
        try:
            result = self.on_decision(decision, tier)
            if inspect.isawaitable(result):
                # Scheduling rather than awaiting keeps a slow callback out of
                # LiteLLM's classifier timeout budget; the decision is already
                # resolved, so nothing downstream depends on it finishing.
                _schedule(result)
        except Exception as exc:  # broad except, deliberately: an observer must not break the observed
            LOGGER.warning("jev-route: on_decision callback failed (%s: %s); ignoring.", type(exc).__name__, exc)


def _schedule(awaitable: Awaitable[Any]) -> None:
    """Best-effort fire-and-forget, with the task referenced so it cannot be GC'd."""
    import asyncio  # deferred import: only needed on the callback path

    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        LOGGER.warning("jev-route: on_decision returned an awaitable outside a running loop; dropping it.")
        awaitable.close()
        return
    task = loop.create_task(_guard(awaitable))
    _PENDING_TASKS.add(task)
    task.add_done_callback(_PENDING_TASKS.discard)


async def _guard(awaitable: Awaitable[Any]) -> None:
    try:
        await awaitable
    except Exception as exc:  # broad except, deliberately
        LOGGER.warning("jev-route: async on_decision callback failed (%s: %s); ignoring.", type(exc).__name__, exc)


#: Strong references to fire-and-forget tasks. asyncio only holds weak ones, and
#: a callback task dropped mid-flight loses a decision an operator asked for.
_PENDING_TASKS: set[Any] = set()


def _policy_wants_cloud(path: Any) -> bool:
    """Whether a policy file asks for the Jev cloud backend.

    Reads only the ``backend.name`` key, and swallows a parse failure: this runs
    at proxy startup purely to decide whether a warning is relevant, and a policy
    that does not parse is reported loudly by :func:`._shared.build_router` on
    the first request anyway. Duplicating that error here would only make the
    boot log noisy about the same problem twice.
    """
    try:
        import yaml  # deferred import: the core already depends on PyYAML

        raw = yaml.safe_load(Path(str(path)).read_text(encoding="utf-8")) or {}
        backend = raw.get("backend") if isinstance(raw, dict) else None
        return isinstance(backend, dict) and str(backend.get("name", "")).lower() == "jev"
    except Exception:  # broad except, deliberately: a hint that cannot be computed is not an error
        return False


def _normalize_tiers(tiers: Iterable[str] | str) -> frozenset[str]:
    """Accept a comma-separated string or any iterable of names."""
    if isinstance(tiers, str):
        return frozenset(part.strip() for part in tiers.split(",") if part.strip())
    if isinstance(tiers, Sequence):
        return frozenset(str(tier).strip() for tier in tiers if str(tier).strip())
    return frozenset(str(tier).strip() for tier in tiers if str(tier).strip())


#: Module-level instance. The proxy resolves ``classifier_plugin:
#: jev_route.integrations.litellm_classifier.classifier`` with
#: ``get_instance_fn``, which requires the last dotted segment to be an
#: attribute holding an *instance* whose ``classify`` is a coroutine function.
classifier = JevRouteClassifier.from_env()

__all__ = [
    "DEFAULT_CLASSIFIER_TIMEOUT_MS",
    "DEFAULT_TIERS",
    "TIERS_ENV_VAR",
    "DecisionCallback",
    "JevRouteClassifier",
    "classifier",
]
